spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product_service
          uri: http://localhost:8081
          predicates:
            - Path=/products/**
        - id: client_service
          uri: http://localhost:8082
          predicates:
            - Path=/clients/**
  security:
    oauth2:
      client:
        registration:
        # Configurações para o provedor de autenticação
        provider:
        # Configurações do provedor
management:
  endpoints:
    web:
      exposure:
        include: "*"