server:
  port: 8081

spring:
  application:
    name: client-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    main:
      allow-circular-references=true:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
