server:
  port: 8082

spring:
  application:
    name: product-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  flyway:
    baseline-on-migrate: true
  main:
    allow-circular-references: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

# JWT Configuration
jwt:
  secret: ${SECRET_JWT}
  expiration: ${TIME_JWT}
